## Fixing "switch"

The current CPS version does not do branch fallthrough. To fix that I
would need to know during construction which arguments are missing.

R native "switch" does a thing where it can end up executing no arguments.

    switch(-1, "one", "two", "three") #takes no branch and returns NULL.

That behavior would be bad to use base R switch as a compiled version of switch, because it would end up falling off and not tailcalling.

Let's see, what about if you initialize a "mapping" at run time and then switch based on a label you pull out of there?

The other problem with switch is that

# making arguments "quotable"

Some constructors might want to get the "quoted" arguments of stuff they aren't going to evaluate. Like "switch", or "for" for that matter.

# ESS versus closxps?!

Apparently the reason I can't just tag a "class" attribute onto a closxp and call that an iteror is.... ESS is fucking with me. If I evaluate a chunk in ESS, it is altering the environment of the resulting closxp. it comes back with the enclosing environment set to the package namespace, instead of the environment that _really_ enclosed it and has its variables. It's weird.

# Name munging

### duplication of trace() and such

Okay, I apparently left off in the midst of munging names. Judging from where I left the `browser()` call, I was finding an argument that transfers "state variables" except that these variables are never updated. If they are never updated then I should be able to dedupe them. But not deduping them will not prevent me from reaching proof of concept with compilation. Deduping of unused variables is a future problem.

However, the other problem with porting over utility variables is what variables are they closed over with? So one resolution might be to treat local functions found in non tail position as a kind of node, and thus capture the variables it itself refers to? Hopefully this doesn't lead to infinite regress? This would be at graph enumeration time.

### Switch in graphs
I need to do something tricky to make my implementation of `switch` traversable by `walk`. Like bquote() out a custom switch_cps. See [switch.R]().

### Speed of walking the graph.

There did appear to be some O(N^2) rearing their heads when walk()ing a graph. Run a profiler? There are definitely some O(n^2) data structures currently in there.

I did something to make myself use hashbags more consistently and noticed a speedup! So there was def some list reallocation going on.

Interestingly, using a list by index isn't much slower than using an env until you get past 100 elements or so. (see ) But s3 dispatch and going through `hashbag()` is quite a bit slower. See [map_timings.Rmd](). So I might want to just use lists instead of hashbags. If I can keep them from having to copy themselves all the time.

### Munging names

So I've gathered all the nodes, or so I claim. I am trying to get a sense of what other things are referenced in each of these nodes.

### Munging state pointers

"state pointers" i.e. closed-over values that contain references to nodes in the graph. These need to be updated.


```{R}

pretty <- function(thing) {
  cat(deparse(unclass(as.list(thing)), width.cutoff = 60), sep="\n")
}

```


One example of a read-only function value is "nonce", "value", "pumpCont", "err" which is in context `_stop` (which actually looks like it should be called `pump` as part of the start set...). I think I am just going to carry that value over literally -- this may result in having the same nonce across several instances of a generator but I think that will be okay. A nonce is never actually called, though.

Hold on, though. I should be picking up that these values are changed, or else why are they initialized to nonce? It thinks `pump$err`, initialized to a nonce, is not a state variable. Why? Because this particular generator _does not reach stop_. Oh! That means it can drop out during inlining.


### doWindup is not copied over

```
> nextElemOr(gc)
Error in doWindup(runPump, ...) (from iteror.R#84) : could not find function "doWindup"
```

On inspecting graph, I find that doWindup is listed as a "call" but not as a "utility"

Now I'm in a process of trying to invoke nextElemOr and seeing what breaks next.

`doWindup` should be translated as a node, though, no? It should be in the start set.
Next we have "assert". I removed the call to assert in pump.r.

### What else stops these from running....

Now I have some problems debugging because all the are happening within runPump's tryCatch thingy.

Now we have "verbose": this line is failing:

```
if (`stop_|verbose`) `stop_|trace`("pump: set unpause\n")
<simpleError in cont(...): object 'stop_|stop' not found>
```

These are failing some

### does generator need to catch?

I know I need to fix the next things. It has been pretty difficult with the big tryCatch wrapped around everything, to get a stack trace. Do we even need a tryCatch around nextElemOr? I turned off the "base winding" for generators (but not for asyncs), and no tests failed. Nwo my stack traces are a bit healthier.

## Emacs locking up when I pause in R debugger

Aargh, something is happening in ess-mode that makes emacs lock up waiting for a response when it's in the debugger. Can be triggered by ess-whatever-completions mode. Is triggered by just having point in an R buffer for a few seconds.

ESS output window keeps saying "Disabling output delimiter because CMD failed to parse."

## it would be nice if name-munging twice were idempotent.

(i.e. ended up with the names and translated functions.) One way to do
that might be to not bother slapping context on the names of nodes in
the special "first" context encountered.)

## Refactor so that trampoline handlers do not use `...` but either take a value or not..

Okay, this `...` business in the handlers might be getting silly. I think for sanity's sake I might have to declare some trampolines take a `val` and others don't. That will be another refactoring (probably before I do codegen)

## Awaiting on a "pr" that doesn't exist gives a "subscript out of bounds"

In this:

      async({
        tryCatch({
          if (await(pr)) {
            return(5)
            not_run <<- FALSE
            5
          } else 4
        }, finally={
          cleanup <<- TRUE
        })
      }

It _should_ give a more comprehensible error. This particular error sounds like something wrong with tryCatch.

## better context/node labels

Would aid debugging comprehension if context / node labels followed the syntax tree more,
were like (try.body.1, try.body,3, try.catch.R) and the like. How

## tryCatch is screwing something up

In compiled mode this generator screws up:

      g <- gen({
        tryCatch({
          yield(5)
          stop("foo")
          yield(6)
        }, error=identity)
        yield(7)
        stop("bar")
        yield(8)
      })


Okay when I try to walk this graph I get fucky things? What's this whole do_expr.n? Okay it looks fine actually. Let's enable verbose and see where it breaks.

Okay it's "finished unexpectedly" after pause. Which means it didn't set the state after getting to pause.

    > > expect_equal(nextElem(g), 7)
    generator: nextElemOr
    pump: run
    catch: windup
    R: stop("foo")
    catch: catch in windup
    catch: stop
    pump: removing from windup list
    catch: unwind
    pump: pause ***********************************************
    Error in obj$nextElemOr(or, ...) : Generator finished unexpectedly

    whereas in non-compiled code it did:

    > > expect_equal(nextElem(g), 7)
    generator: nextElemOr
    pump: run
    catch: windup
    R: stop("foo")
    catch: catch in windup
    catch: stop
    pump: removing from windup list
    catch: unwind
    pump: continuing after unwind ********************************************
    R: identity
    catch: calling error handler
    pump: set continue
    pump: continue
    R: 7
    yield
    generator: yield
    pump: set unpause
    pump: pause

I think this is a case of `do_windup` not being translated, printf showing me that. Yeah, `do_windup` should be a node but the graph draws it as a variable. `windup` is a trampoline that takes _two_ pointers, one to add to the windup list and another to continue.

stop: could not find function "_do_windup.tryCatch#parent.frame"

okay, but _then_ it _also_ resolves the wrong promise.

Okay now we're at "could not find function `stop_`.

Also, error text is not being propagated somehow. I guess that's because it's an internal error. But the tryCatch should still get it.

Okay a couple things aren't right when we get to `_return`. Here's how `do_windup` is being translated:

    function (cont, ...)
    {
        list(`_do_expr.1.awaited.then.2.ifTrue.1.do_finally.2`, ...)
        `entry#trace`("finally: windup\n")
        on.exit(`entry#trace`("finally: unwind\n"))
        tryCatch(`_do_expr.1.awaited.then.2.ifTrue.1.do_finally.2`(...),
            error = function(err) {
                `entry#trace`("finally: catch in windup\n")
                stop_(err)
            })
        NULL
    }

surely that should be list(cont, ...), and stop_ is not being translated as a call either. And the function is apparently being invoked as cont(cont=cont)??


So I think the issue is I'm not walking into anonymous functions.

Okay we're back to the wrong "resolve" being called.

Whick means we're passing the wrong handler to register...

So it looks like munged `resolve#pump` goes to the old pump.

Okay, when we are walking over a compiled "async" it thinks its "pump" is an external function and it copies it over. I changed it to `move_value` which at least checks fora  node pointer.

Now, however, my generator is failing to find corresponding local names `stop_` in the munged graph. The compiled graph gives it a local name of "nextElemOr#stop." That's definitely not its local name. nextElemOr#stop should be translated to "stop" during munge?

So I think this is a consequence of not deduping. Two identical `stop_` functions are winding up transferred. Doing a direct move hid this -- nextElemOr#stop was a leaky pointer so it did not previously show up when scanning for a local name for "stop".

Also, it was because I used "stop" instead of "base::stop" in one spot. So no need to dedupe yet,

And the same thing is happening with "resolve#pump". in the async. Which points to...
